{"message":"Day2dayPaymentEntry.match is not a function","stack":"TypeError: Day2dayPaymentEntry.match is not a function\n    at router.get (/home/ec2-user/nodemongo/routes/day2day.js:94:63)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:137:13)\n    at module.exports (/home/ec2-user/nodemongo/middleware/authentication.js:11:5)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at /home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:47:12)","level":"error","timestamp":"2018-11-29T09:11:15.156Z"}
{"message":"Day2dayPaymentEntry.match is not a function","stack":"TypeError: Day2dayPaymentEntry.match is not a function\n    at router.get (/home/ec2-user/nodemongo/routes/day2day.js:94:63)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:137:13)\n    at module.exports (/home/ec2-user/nodemongo/middleware/authentication.js:11:5)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/ec2-user/nodemongo/node_modules/express/lib/router/route.js:112:3)\n    at newFn (/home/ec2-user/nodemongo/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/home/ec2-user/nodemongo/node_modules/express/lib/router/layer.js:95:5)\n    at /home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:335:12)\n    at next (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:174:3)\n    at router (/home/ec2-user/nodemongo/node_modules/express/lib/router/index.js:47:12)","level":"error","timestamp":"2018-12-02T12:43:30.595Z"}
